name: Release

on:
  push:
    tags:
      - "v*.*.*"
  workflow_dispatch:
    inputs:
      version:
        description: "Version to release (e.g., v0.3.3)"
        required: true
        type: string

permissions:
  contents: write

env:
  CARGO_TERM_COLOR: always

jobs:
  build-and-release:
    strategy:
      matrix:
        include:
          - os: windows-latest
            target: x86_64-pc-windows-gnu
            use_bundle: false
            archive_ext: zip
            executable_ext: .exe
          - os: macos-latest
            target: x86_64-apple-darwin
            use_bundle: true
            archive_ext: tar.gz
            executable_ext: ""
          - os: macos-latest
            target: aarch64-apple-darwin
            use_bundle: true
            archive_ext: tar.gz
            executable_ext: ""
          - os: ubuntu-latest
            target: x86_64-unknown-linux-gnu
            use_bundle: false
            archive_ext: tar.gz
            executable_ext: ""
          - os: ubuntu-latest
            target: aarch64-unknown-linux-gnu
            use_bundle: false
            archive_ext: tar.gz
            executable_ext: ""

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Get version
        id: get_version
        shell: bash
        run: |
          if [ "${{ github.event_name }}" = "workflow_dispatch" ]; then
            echo "version=${{ github.event.inputs.version }}" >> $GITHUB_OUTPUT
          else
            echo "version=${GITHUB_REF#refs/tags/}" >> $GITHUB_OUTPUT
          fi

      - name: Setup Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: ${{ matrix.target }}

      - name: Setup Windows GNU toolchain
        if: matrix.os == 'windows-latest'
        run: |
          rustup toolchain install stable-x86_64-pc-windows-gnu
          rustup default stable-x86_64-pc-windows-gnu

      - name: Setup MinGW (Windows)
        if: matrix.os == 'windows-latest'
        uses: msys2/setup-msys2@v2
        with:
          msystem: MINGW64
          update: true
          install: >-
            mingw-w64-x86_64-gcc
            mingw-w64-x86_64-toolchain
            mingw-w64-x86_64-pkg-config

      - name: Configure MinGW environment (Windows)
        if: matrix.os == 'windows-latest'
        shell: bash
        run: |
          echo "C:/msys64/mingw64/bin" >> $GITHUB_PATH
          echo "CC=gcc" >> $GITHUB_ENV
          echo "CXX=g++" >> $GITHUB_ENV
          echo "CARGO_TARGET_X86_64_PC_WINDOWS_GNU_LINKER=gcc" >> $GITHUB_ENV

      - name: Install cargo-bundle (macOS only)
        if: matrix.use_bundle
        run: cargo install cargo-bundle

      - name: Install cross-compilation dependencies (Linux)
        if: matrix.os == 'ubuntu-latest' && matrix.target == 'aarch64-unknown-linux-gnu'
        run: |
          sudo apt-get update
          sudo apt-get install -y gcc-aarch64-linux-gnu

      - name: Configure cross-compilation (Linux aarch64)
        if: matrix.os == 'ubuntu-latest' && matrix.target == 'aarch64-unknown-linux-gnu'
        run: |
          mkdir -p ~/.cargo
          cat > ~/.cargo/config.toml << EOF
          [target.aarch64-unknown-linux-gnu]
          linker = "aarch64-linux-gnu-gcc"
          EOF

      - name: Cache cargo dependencies
        uses: Swatinem/rust-cache@v2
        with:
          key: ${{ matrix.target }}

      - name: Build (bundle for macOS)
        if: matrix.use_bundle
        run: cargo bundle --release --target ${{ matrix.target }}

      - name: Build (regular for other platforms)
        if: ${{ !matrix.use_bundle }}
        run: cargo build --release --target ${{ matrix.target }}

      - name: Prepare release directory
        shell: bash
        run: |
          VERSION=${{ steps.get_version.outputs.version }}
          RELEASE_DIR="qualetize-gui-${VERSION}-${{ matrix.target }}"
          mkdir -p "${RELEASE_DIR}"

          if [ "${{ matrix.use_bundle }}" = "true" ]; then
            # For macOS bundle
            cp -r target/${{ matrix.target }}/release/bundle/osx/QualetizeGUI.app "${RELEASE_DIR}/"
          else
            # For other platforms
            if [ "${{ matrix.os }}" = "windows-latest" ]; then
              cp target/${{ matrix.target }}/release/QualetizeGUI${{ matrix.executable_ext }} "${RELEASE_DIR}/"
            else
              cp target/${{ matrix.target }}/release/QualetizeGUI "${RELEASE_DIR}/"
            fi
          fi

          echo "RELEASE_DIR=${RELEASE_DIR}" >> $GITHUB_ENV

      - name: Create archive (Windows)
        if: matrix.archive_ext == 'zip'
        id: create_archive_win
        shell: bash
        run: |
          VERSION=${{ steps.get_version.outputs.version }}
          ARCHIVE_NAME="qualetize-gui-${VERSION}-${{ matrix.target }}"
          python -c "
          import zipfile
          import os
          import sys

          release_dir = '${RELEASE_DIR}'
          archive_name = '${ARCHIVE_NAME}.zip'

          with zipfile.ZipFile(archive_name, 'w', zipfile.ZIP_DEFLATED, compresslevel=6) as zipf:
              for root, dirs, files in os.walk(release_dir):
                  for file in files:
                      file_path = os.path.join(root, file)
                      arc_name = os.path.relpath(file_path, release_dir)
                      zipf.write(file_path, arc_name)

          print(f'Created {archive_name}')
          "
          echo "archive_name=${ARCHIVE_NAME}.zip" >> $GITHUB_OUTPUT

      - name: Create archive (Unix)
        if: matrix.archive_ext == 'tar.gz'
        id: create_archive_unix
        shell: bash
        run: |
          VERSION=${{ steps.get_version.outputs.version }}
          ARCHIVE_NAME="qualetize-gui-${VERSION}-${{ matrix.target }}"
          tar -czf "${ARCHIVE_NAME}.tar.gz" --exclude='.DS_Store' "${RELEASE_DIR}"
          echo "archive_name=${ARCHIVE_NAME}.tar.gz" >> $GITHUB_OUTPUT

      - name: Upload to Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ steps.get_version.outputs.version }}
          name: QualetizeGUI ${{ steps.get_version.outputs.version }}
          files: ${{ steps.create_archive_win.outputs.archive_name || steps.create_archive_unix.outputs.archive_name }}
          draft: false
          prerelease: false
          make_latest: true
          generate_release_notes: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
